### ISSUE TITLE
Mod doesn't detect plugin when installed on a server network

### ISSUE THREAD

**Issue by rinyafii** [sammyshear/Waypoints4Homes#2] opened 2023-07-20 11:13 UTC
I wanted to try this mod out so I installed it on my survival server, but in order to join you first need to go through the hub server which doesn't have it, so it doesn't work. It seems the mod doesn't detect when you change between servers in a server network.

**Comment by sammyshear** [comment] 2023-07-20 12:21
I run this plugin on a server behind a velocity proxy with no issues, so this is interesting. Are there any errors in the console? I'm also not sure why this would be a problem on other proxies either, but if there's any more information you can give me that would be great. Thanks for the report.

**Comment by rinyafii** [comment] 2023-07-20 12:50
There isn't anything in the server console other than the message that it loaded. There also isn't anything in the game log when I join.

**Comment by rinyafii** [comment] 2023-07-20 13:00
Here's the [client](https://mclo.gs/Fy9hPJM) and [server](https://mclo.gs/IH1xhEb) logs with every other mod/plugin (other than Xareos & EssensialsX) removed.

**Comment by sammyshear** [comment] 2023-07-20 13:43
Interesting, I suspect this is actually a bug with the bukkit plugin and I made a mistake when doing the logic for detecting the homes plugin. Just for the sake of covering all bases though, can you make sure that in the Waypoints4Homes/config.yml file that HuskHomes is enabled. It's possible that's the issue although more than likely it's more to do with a mistake on my end.

**Comment by rinyafii** [comment] 2023-07-20 13:49
Switching the config doesn't do anything, I had already tried that just in case (I use Essentials anyway, but I checked to see if enabling HuskHomes would do anything, it didn't)

**Comment by sammyshear** [comment] 2023-07-20 13:54
Oh I'm sorry, I misunderstood your last comment. I'll definitely take a look at this to see if I can reproduce and fix it. I'm away from my computer right now (writing these on my phone), but when I get the chance I'll take a look. It's also possible that my last update to the fabric end would have broken things with Xaeros, but when testing it on my end before the release it didn't seem to have any issues with essentially the same setup, so this is an interesting bug to me.

**Comment by sammyshear** [comment] 2023-07-20 14:32
I was mostly correct,  I had made it almost impossible for Essentials to be hooked into by the plugin in the previous version, but since I was mostly testing HuskHomes I didn't catch it. It should be fixed in the latest release, v1.0.9, but if you are still having issues let me know.

**Closed as completed by sammyshear** 2023-07-20 14:32 UTC
Labels: bug
